Extend ecutils
coingaming/hm-crypto pull request #10
Opened 2021-02-05 10:18 UTC by oleg-kiviljov

2021-02-05 11:53 UTC, tim2CF commented on lib/hm_crypto/ec_utils/ec_utils.ex
> +  def public_key_from_private_key(private_key) when is_binary(private_key) do
I'm not sure about naming of this clause. Maybe `public_key_from_private_key_pem` of something similar can be better. PEM is not the only binary/text untyped EC key format, we also are using DER as well.

2021-02-09 11:53 UTC, ischepin reviewed
Please fill in PR description. Everything else looks good.

2021-02-09 12:03 UTC, ischepin requested changes

2021-02-09 12:03 UTC, ischepin commented on lib/hm_crypto.ex
> +  @spec sign!(binary(), digest_type(), HmCrypto.PublicKey.key()) :: binary()
I think the spec is incorrect here; it says 3rd arg is public key but function header says its private key. Obviously you need a private key to sign something. Could you please fix it?

2021-02-09 12:55 UTC, oleg-kiviljov commented on lib/hm_crypto.ex
> +  @spec sign!(binary(), digest_type(), HmCrypto.PublicKey.key()) :: binary()
adde PrivateKey module

2021-02-12 09:37 UTC, merged